const data = [
  {
    id: 1,
    fullName: "Sonny Finci",
    avatar: "https://robohash.org/essesuntid.png?size=50x50&set=set1",
    university: "West Coast University",
    department: "Product Management",
  },
  {
    id: 2,
    fullName: "Kipp Hatz",
    avatar:
      "https://robohash.org/fugiatrecusandaeducimus.png?size=50x50&set=set1",
    university: "Universidad Tecnológica Oteima",
    department: "Accounting",
  },
  {
    id: 3,
    fullName: "Konstanze Diggles",
    avatar: "https://robohash.org/etquiveritatis.png?size=50x50&set=set1",
    university: "Durham College",
    department: "Services",
  },
  {
    id: 4,
    fullName: "Tom Lashmar",
    avatar:
      "https://robohash.org/solutamolestiaedistinctio.png?size=50x50&set=set1",
    university: "Pannnasatra University of Cambodia",
    department: "Accounting",
  },
  {
    id: 5,
    fullName: "Blanche Hasted",
    avatar: "https://robohash.org/porrofugiatrepellat.png?size=50x50&set=set1",
    university: "Brandman University",
    department: "Business Development",
  },
  {
    id: 6,
    fullName: "Corrinne Revan",
    avatar: "https://robohash.org/voluptasullamimpedit.png?size=50x50&set=set1",
    university: "Institut des Hautes Etudes de Management",
    department: "Human Resources",
  },
  {
    id: 7,
    fullName: "Kimbra Adolf",
    avatar: "https://robohash.org/eumutquae.png?size=50x50&set=set1",
    university: "Tottori University",
    department: "Marketing",
  },
  {
    id: 8,
    fullName: "Anne-marie Rubert",
    avatar: "https://robohash.org/modiassumendaquo.png?size=50x50&set=set1",
    university: "University of San Francisco",
    department: "Legal",
  },
  {
    id: 9,
    fullName: "Mack McCrea",
    avatar: "https://robohash.org/modiminuset.png?size=50x50&set=set1",
    university: "Hiroshima University of Economics",
    department: "Support",
  },
  {
    id: 10,
    fullName: "Norman Meugens",
    avatar: "https://robohash.org/rerumdelenitieum.png?size=50x50&set=set1",
    university: "Centro Universitario de Occidente",
    department: "Accounting",
  },
  {
    id: 11,
    fullName: "Jada Stoves",
    avatar:
      "https://robohash.org/placeatatqueblanditiis.png?size=50x50&set=set1",
    university: "Technological University (Meikhtila)",
    department: "Training",
  },
  {
    id: 12,
    fullName: "Shari Alexandrou",
    avatar:
      "https://robohash.org/consequaturdoloripsam.png?size=50x50&set=set1",
    university: "Instituto Tecnologico de Minatitlan",
    department: "Support",
  },
  {
    id: 13,
    fullName: "Muriel Hawton",
    avatar:
      "https://robohash.org/nobisconsequaturdolores.png?size=50x50&set=set1",
    university: "Russian State Hydrometeorological University",
    department: "Business Development",
  },
  {
    id: 14,
    fullName: "Felecia Beasleigh",
    avatar:
      "https://robohash.org/nisiconsequunturrerum.png?size=50x50&set=set1",
    university: "National Aerospace University Kharkov Aviation Institute",
    department: "Accounting",
  },
  {
    id: 15,
    fullName: "Gardner Mellenby",
    avatar:
      "https://robohash.org/doloresarchitectocommodi.png?size=50x50&set=set1",
    university: "College of St. Catherine",
    department: "Accounting",
  },
  {
    id: 16,
    fullName: "Marten Constance",
    avatar: "https://robohash.org/nequenisia.png?size=50x50&set=set1",
    university: "Universidad Ulises Francisco Espaillat",
    department: "Engineering",
  },
  {
    id: 17,
    fullName: "Thatcher Tythe",
    avatar: "https://robohash.org/ametquiaconsectetur.png?size=50x50&set=set1",
    university: "Technological University (Lashio)",
    department: "Accounting",
  },
  {
    id: 18,
    fullName: "Siouxie Rens",
    avatar: "https://robohash.org/sitestut.png?size=50x50&set=set1",
    university: "Institut Supérieur Agricole de Beauvais",
    department: "Marketing",
  },
  {
    id: 19,
    fullName: "Heda Bossom",
    avatar: "https://robohash.org/ducimusquisin.png?size=50x50&set=set1",
    university: "Université de l'Uélé",
    department: "Training",
  },
  {
    id: 20,
    fullName: "Maria Mathiot",
    avatar: "https://robohash.org/totamvoluptasaperiam.png?size=50x50&set=set1",
    university: "Université de Franche-Comté",
    department: "Legal",
  },
  {
    id: 21,
    fullName: "Guinevere Aucoate",
    avatar:
      "https://robohash.org/etvoluptasconsequatur.png?size=50x50&set=set1",
    university: "Saga University",
    department: "Product Management",
  },
  {
    id: 22,
    fullName: "Delilah Feenan",
    avatar: "https://robohash.org/mollitiamaximesaepe.png?size=50x50&set=set1",
    university: "New England Conservatory of Music",
    department: "Marketing",
  },
  {
    id: 23,
    fullName: "Griz Aked",
    avatar: "https://robohash.org/inadvoluptas.png?size=50x50&set=set1",
    university: "Yerevan State University",
    department: "Engineering",
  },
  {
    id: 24,
    fullName: "Alecia Micallef",
    avatar: "https://robohash.org/ametlaudantiumnobis.png?size=50x50&set=set1",
    university: "Centro Universitario de Occidente",
    department: "Human Resources",
  },
  {
    id: 25,
    fullName: "Kacey Danilchik",
    avatar: "https://robohash.org/sequiisteexcepturi.png?size=50x50&set=set1",
    university: "Hokkaido University of Education",
    department: "Research and Development",
  },
  {
    id: 26,
    fullName: "Jerome Emerson",
    avatar: "https://robohash.org/fugiatblanditiisodit.png?size=50x50&set=set1",
    university: "Rocky Mountain College of Art and Design",
    department: "Accounting",
  },
  {
    id: 27,
    fullName: "Gavrielle Pringle",
    avatar: "https://robohash.org/enimminusnulla.png?size=50x50&set=set1",
    university: "Maharaja Sayajirao University of Baroda",
    department: "Business Development",
  },
  {
    id: 28,
    fullName: "Lucila Berford",
    avatar: "https://robohash.org/quocupiditatesit.png?size=50x50&set=set1",
    university: "Beirut Arab University",
    department: "Human Resources",
  },
  {
    id: 29,
    fullName: "Hershel Ollerenshaw",
    avatar: "https://robohash.org/repudiandaesitquia.png?size=50x50&set=set1",
    university: "Academy of Public Administration",
    department: "Services",
  },
  {
    id: 30,
    fullName: "Elvira Rustman",
    avatar:
      "https://robohash.org/veritatismollitiaexpedita.png?size=50x50&set=set1",
    university: "Universidad del Istmo",
    department: "Training",
  },
  {
    id: 31,
    fullName: "Janelle Kennefick",
    avatar:
      "https://robohash.org/nobispraesentiumnesciunt.png?size=50x50&set=set1",
    university: "University of Mosul",
    department: "Services",
  },
  {
    id: 32,
    fullName: "Lena Reynolds",
    avatar: "https://robohash.org/enimrepudiandaenemo.png?size=50x50&set=set1",
    university: "Ecole Supérieure d'Ingénieurs en Génie Electrique",
    department: "Training",
  },
  {
    id: 33,
    fullName: "Rivi Annies",
    avatar: "https://robohash.org/hicaccusamusnisi.png?size=50x50&set=set1",
    university: "University of Maryland Medicine",
    department: "Engineering",
  },
  {
    id: 34,
    fullName: "Evangelin Collar",
    avatar: "https://robohash.org/nesciuntvelitab.png?size=50x50&set=set1",
    university: "Palmer College of Chiropractic",
    department: "Product Management",
  },
  {
    id: 35,
    fullName: "Winnie Burles",
    avatar: "https://robohash.org/saepepossimusex.png?size=50x50&set=set1",
    university: "Universidad de Flores - Buenos Aires",
    department: "Marketing",
  },
  {
    id: 36,
    fullName: "Mickey Moring",
    avatar:
      "https://robohash.org/doloremquequasiexplicabo.png?size=50x50&set=set1",
    university: "Langston University",
    department: "Legal",
  },
  {
    id: 37,
    fullName: "Ambrose Cattermoul",
    avatar:
      "https://robohash.org/perferendisevenietvoluptas.png?size=50x50&set=set1",
    university: "University of East",
    department: "Support",
  },
  {
    id: 38,
    fullName: "Evyn Nettles",
    avatar: "https://robohash.org/doloribusautfacere.png?size=50x50&set=set1",
    university: "Kannada University",
    department: "Training",
  },
  {
    id: 39,
    fullName: "Nessy Basey",
    avatar: "https://robohash.org/quoquidemiste.png?size=50x50&set=set1",
    university: "National Technical University of Athens",
    department: "Engineering",
  },
  {
    id: 40,
    fullName: "Alayne Keysall",
    avatar: "https://robohash.org/omnisetexpedita.png?size=50x50&set=set1",
    university: "Universidad Latinoamericana de Ciencia y Tecnologia, Panamá",
    department: "Engineering",
  },
  {
    id: 41,
    fullName: "Fabian Bravery",
    avatar:
      "https://robohash.org/autaccusamustemporibus.png?size=50x50&set=set1",
    university: "United States International University",
    department: "Accounting",
  },
  {
    id: 42,
    fullName: "Robinia Joselson",
    avatar: "https://robohash.org/natusminimarepellat.png?size=50x50&set=set1",
    university: "Royal Danish Academy of Music",
    department: "Human Resources",
  },
  {
    id: 43,
    fullName: "Joannes Addinall",
    avatar:
      "https://robohash.org/voluptatumeaqueconsequatur.png?size=50x50&set=set1",
    university: "Lake Forest Graduate School of Management",
    department: "Training",
  },
  {
    id: 44,
    fullName: "Allie Barkus",
    avatar:
      "https://robohash.org/dolorespariaturconsectetur.png?size=50x50&set=set1",
    university: "Eastern Michigan University",
    department: "Marketing",
  },
  {
    id: 45,
    fullName: "Ginni Caghy",
    avatar: "https://robohash.org/laborumprovidentqui.png?size=50x50&set=set1",
    university: "Institut Supérieur de Gestion de Tunis",
    department: "Legal",
  },
  {
    id: 46,
    fullName: "Carolan Grisedale",
    avatar: "https://robohash.org/etestqui.png?size=50x50&set=set1",
    university: "Universidad Internacional del Ecuador",
    department: "Training",
  },
  {
    id: 47,
    fullName: "Jessica Glasner",
    avatar: "https://robohash.org/magnamoptiodolor.png?size=50x50&set=set1",
    university: "Kermanshah University of Technology",
    department: "Services",
  },
  {
    id: 48,
    fullName: "Trescha de Keyser",
    avatar: "https://robohash.org/ullamquasidicta.png?size=50x50&set=set1",
    university: "Upper Nile University",
    department: "Services",
  },
  {
    id: 49,
    fullName: "Constance Hardcastle",
    avatar: "https://robohash.org/siteumnostrum.png?size=50x50&set=set1",
    university: "Tibet Tibetan Medical College",
    department: "Engineering",
  },
  {
    id: 50,
    fullName: "Cahra Durante",
    avatar: "https://robohash.org/magnamnullaiste.png?size=50x50&set=set1",
    university: "Bethel College McKenzie",
    department: "Marketing",
  },
  {
    id: 51,
    fullName: "Peadar Whitney",
    avatar:
      "https://robohash.org/necessitatibusquidolorem.png?size=50x50&set=set1",
    university: "Rockford College",
    department: "Support",
  },
  {
    id: 52,
    fullName: "Dorthy Banfill",
    avatar: "https://robohash.org/ipsamliberoesse.png?size=50x50&set=set1",
    university: "Sultanah Bahiyah Polytechnic",
    department: "Services",
  },
  {
    id: 53,
    fullName: "Lowell Taillant",
    avatar: "https://robohash.org/eosquidolorem.png?size=50x50&set=set1",
    university: "Universidad de San Pedro Sula",
    department: "Engineering",
  },
  {
    id: 54,
    fullName: "Eryn Richmond",
    avatar:
      "https://robohash.org/architectovoluptasnon.png?size=50x50&set=set1",
    university: "Antioch University",
    department: "Sales",
  },
  {
    id: 55,
    fullName: "Natala Fucher",
    avatar: "https://robohash.org/utquamest.png?size=50x50&set=set1",
    university: 'University of Shkodra "Luigj Gurakuqi"',
    department: "Accounting",
  },
  {
    id: 56,
    fullName: "Reinaldo Straffon",
    avatar: "https://robohash.org/sedteneturquos.png?size=50x50&set=set1",
    university: "Konkan Agricultural University",
    department: "Engineering",
  },
  {
    id: 57,
    fullName: "Teador Challender",
    avatar: "https://robohash.org/odioquisin.png?size=50x50&set=set1",
    university: "University of Messina",
    department: "Business Development",
  },
  {
    id: 58,
    fullName: "Crissie Grigs",
    avatar: "https://robohash.org/beataeutautem.png?size=50x50&set=set1",
    university: "Georgia School of Professional Psychology",
    department: "Services",
  },
  {
    id: 59,
    fullName: "Kelly Harse",
    avatar:
      "https://robohash.org/voluptatibusconsequatursimilique.png?size=50x50&set=set1",
    university: "Academy of Sports and Physical Training",
    department: "Business Development",
  },
  {
    id: 60,
    fullName: "Evelin Sergeant",
    avatar:
      "https://robohash.org/pariaturofficiisconsequatur.png?size=50x50&set=set1",
    university: "National Cheng Kung University",
    department: "Sales",
  },
  {
    id: 61,
    fullName: "Tyne Edling",
    avatar: "https://robohash.org/rerumsolutarem.png?size=50x50&set=set1",
    university: "Kaduna State University",
    department: "Engineering",
  },
  {
    id: 62,
    fullName: "Moreen Piggin",
    avatar:
      "https://robohash.org/molestiasanimiofficiis.png?size=50x50&set=set1",
    university: "Southeast University",
    department: "Business Development",
  },
  {
    id: 63,
    fullName: "Matthieu Pacher",
    avatar: "https://robohash.org/nesciuntdolorfugit.png?size=50x50&set=set1",
    university: "Mutesa 1 Royal University",
    department: "Human Resources",
  },
  {
    id: 64,
    fullName: "Muffin Tye",
    avatar: "https://robohash.org/enimetvitae.png?size=50x50&set=set1",
    university: "State University of Management",
    department: "Research and Development",
  },
  {
    id: 65,
    fullName: "Geoff Flecknoe",
    avatar: "https://robohash.org/quioptiosit.png?size=50x50&set=set1",
    university: "The American University in London",
    department: "Product Management",
  },
  {
    id: 66,
    fullName: "Yehudit Rodolf",
    avatar: "https://robohash.org/veniamdolorvoluptate.png?size=50x50&set=set1",
    university: "University of Mary",
    department: "Services",
  },
  {
    id: 67,
    fullName: "Obediah Costock",
    avatar: "https://robohash.org/inciduntataut.png?size=50x50&set=set1",
    university: "University of Rio Grande",
    department: "Marketing",
  },
  {
    id: 68,
    fullName: "Wyatan Allpress",
    avatar: "https://robohash.org/idarchitectofacere.png?size=50x50&set=set1",
    university: "Russell Berrie Nanotechnology Institute",
    department: "Legal",
  },
  {
    id: 69,
    fullName: "Miran Lazer",
    avatar: "https://robohash.org/quorerumomnis.png?size=50x50&set=set1",
    university: "Lee University",
    department: "Human Resources",
  },
  {
    id: 70,
    fullName: "Bernarr Pickthorn",
    avatar:
      "https://robohash.org/perferendisnisiconsequuntur.png?size=50x50&set=set1",
    university: "Konkan Agricultural University",
    department: "Product Management",
  },
  {
    id: 71,
    fullName: "Freda Cawthron",
    avatar: "https://robohash.org/quiautaliquid.png?size=50x50&set=set1",
    university: "Andrassy Gyula German Speaking University Budapest",
    department: "Engineering",
  },
  {
    id: 72,
    fullName: "Atlanta Whightman",
    avatar:
      "https://robohash.org/deseruntrepellendusatque.png?size=50x50&set=set1",
    university: "Geneva Business School",
    department: "Marketing",
  },
  {
    id: 73,
    fullName: "Viviyan Dacre",
    avatar: "https://robohash.org/animiliberototam.png?size=50x50&set=set1",
    university: "Fu Jen Catholic University",
    department: "Support",
  },
  {
    id: 74,
    fullName: "Hilary Benz",
    avatar:
      "https://robohash.org/consecteturfugavoluptatem.png?size=50x50&set=set1",
    university: "Université de M'sila",
    department: "Training",
  },
  {
    id: 75,
    fullName: "Salli Mackneis",
    avatar:
      "https://robohash.org/ullamasperioresnesciunt.png?size=50x50&set=set1",
    university: "University of Colorado at Denver",
    department: "Support",
  },
  {
    id: 76,
    fullName: "Kerr Walisiak",
    avatar: "https://robohash.org/velitconsequaturamet.png?size=50x50&set=set1",
    university: "Colby-Sawyer College",
    department: "Research and Development",
  },
  {
    id: 77,
    fullName: "Ardith Caslin",
    avatar: "https://robohash.org/solutaodioaut.png?size=50x50&set=set1",
    university: "Gyeongju University",
    department: "Engineering",
  },
  {
    id: 78,
    fullName: "Tracey Roggeman",
    avatar: "https://robohash.org/quoarepudiandae.png?size=50x50&set=set1",
    university: "Birzeit University",
    department: "Business Development",
  },
  {
    id: 79,
    fullName: "Gale Pamphilon",
    avatar: "https://robohash.org/atculpaet.png?size=50x50&set=set1",
    university: "Universidad de Antioquía",
    department: "Sales",
  },
  {
    id: 80,
    fullName: "Inna Warwicker",
    avatar: "https://robohash.org/etdoloreseaque.png?size=50x50&set=set1",
    university: "Séchenyi István University",
    department: "Support",
  },
  {
    id: 81,
    fullName: "Sayers Kinnaird",
    avatar: "https://robohash.org/dolorumteneturaut.png?size=50x50&set=set1",
    university: "University of Louisiana at Monroe",
    department: "Services",
  },
  {
    id: 82,
    fullName: "Lidia Robelow",
    avatar: "https://robohash.org/velnesciuntaut.png?size=50x50&set=set1",
    university: "Faculdades Integradas UPIS",
    department: "Product Management",
  },
  {
    id: 83,
    fullName: "Edyth Canfer",
    avatar: "https://robohash.org/sitquiacumque.png?size=50x50&set=set1",
    university: "Wayamba University of Sri Lanka ",
    department: "Human Resources",
  },
  {
    id: 84,
    fullName: "Staffard Antosch",
    avatar:
      "https://robohash.org/doloremquiadignissimos.png?size=50x50&set=set1",
    university: "Cosmopolitan University",
    department: "Training",
  },
  {
    id: 85,
    fullName: "Rodolph Glozman",
    avatar: "https://robohash.org/voluptatumquinatus.png?size=50x50&set=set1",
    university: "Universidad Católica San Antonio",
    department: "Product Management",
  },
  {
    id: 86,
    fullName: "Llywellyn Offer",
    avatar: "https://robohash.org/nihilmaioresqui.png?size=50x50&set=set1",
    university: "Dominican University",
    department: "Accounting",
  },
  {
    id: 87,
    fullName: "Thorin Give",
    avatar:
      "https://robohash.org/doloreslaudantiumveniam.png?size=50x50&set=set1",
    university: "International University",
    department: "Legal",
  },
  {
    id: 88,
    fullName: "Ky Lydiard",
    avatar:
      "https://robohash.org/accusantiumquasireprehenderit.png?size=50x50&set=set1",
    university: "Osaka Shoin Women's College",
    department: "Human Resources",
  },
  {
    id: 89,
    fullName: "Susan Pickburn",
    avatar: "https://robohash.org/consectetureoscum.png?size=50x50&set=set1",
    university: "New York College of Podiatric Medicine",
    department: "Marketing",
  },
  {
    id: 90,
    fullName: "Nikolai Jerzykiewicz",
    avatar:
      "https://robohash.org/voluptatumeiusadipisci.png?size=50x50&set=set1",
    university: "Nippon Medical School",
    department: "Engineering",
  },
  {
    id: 91,
    fullName: "Roselle Snelman",
    avatar:
      "https://robohash.org/cumquelaboriosamprovident.png?size=50x50&set=set1",
    university: "Angkor University",
    department: "Accounting",
  },
  {
    id: 92,
    fullName: "Bay Caps",
    avatar: "https://robohash.org/veniamquisvoluptatem.png?size=50x50&set=set1",
    university: "Yashawantrao Chavan Maharashtra Open University",
    department: "Training",
  },
  {
    id: 93,
    fullName: "Symon Whelpdale",
    avatar: "https://robohash.org/vitaeadsed.png?size=50x50&set=set1",
    university: "Art Center College of Design",
    department: "Engineering",
  },
  {
    id: 94,
    fullName: "Charlton Tewkesbury.",
    avatar: "https://robohash.org/culpaquoaspernatur.png?size=50x50&set=set1",
    university: "Carroll College Waukesha",
    department: "Engineering",
  },
  {
    id: 95,
    fullName: "Bathsheba Ohm",
    avatar: "https://robohash.org/quiautvoluptatem.png?size=50x50&set=set1",
    university: "Bilecik University",
    department: "Business Development",
  },
  {
    id: 96,
    fullName: "Aluino Oneile",
    avatar: "https://robohash.org/similiqueeiustotam.png?size=50x50&set=set1",
    university: "Jordan University of Science and Technology",
    department: "Product Management",
  },
  {
    id: 97,
    fullName: "Francis Bosomworth",
    avatar:
      "https://robohash.org/voluptatemvoluptatemeligendi.png?size=50x50&set=set1",
    university: "Fukui Medical School",
    department: "Legal",
  },
  {
    id: 98,
    fullName: "Marijn Fursse",
    avatar: "https://robohash.org/estasperioresmaiores.png?size=50x50&set=set1",
    university: "Cornish College of the Arts",
    department: "Sales",
  },
  {
    id: 99,
    fullName: "Franchot Biskupski",
    avatar: "https://robohash.org/abvoluptasautem.png?size=50x50&set=set1",
    university: "Aarhus University",
    department: "Accounting",
  },
  {
    id: 100,
    fullName: "Eleanora Shear",
    avatar: "https://robohash.org/facerefugiteos.png?size=50x50&set=set1",
    university: "Technological Education Institute of Piraeus",
    department: "Services",
  },
  {
    id: 101,
    fullName: "Joete Snasel",
    avatar: "https://robohash.org/quodsednostrum.png?size=50x50&set=set1",
    university: "University of Nizwa",
    department: "Product Management",
  },
  {
    id: 102,
    fullName: "Lesly Strettle",
    avatar: "https://robohash.org/numquaminsimilique.png?size=50x50&set=set1",
    university: "Kharkiv National University of Radio Electronics",
    department: "Business Development",
  },
  {
    id: 103,
    fullName: "Charline Brychan",
    avatar: "https://robohash.org/eteligendiipsum.png?size=50x50&set=set1",
    university: "Misr International University",
    department: "Accounting",
  },
  {
    id: 104,
    fullName: "Morris Whyatt",
    avatar: "https://robohash.org/autquodeos.png?size=50x50&set=set1",
    university: "Idaho State University",
    department: "Engineering",
  },
  {
    id: 105,
    fullName: "Adele Geraldo",
    avatar: "https://robohash.org/rerumautemquibusdam.png?size=50x50&set=set1",
    university: "Agricultural University of Plovdiv",
    department: "Marketing",
  },
  {
    id: 106,
    fullName: "Robin Jurasek",
    avatar: "https://robohash.org/estutest.png?size=50x50&set=set1",
    university: "Zanjan Institute for Advanced Studies in Basic Sciences",
    department: "Marketing",
  },
  {
    id: 107,
    fullName: "Odilia Beeching",
    avatar: "https://robohash.org/accusamusautin.png?size=50x50&set=set1",
    university: "Université Catholique de Lille",
    department: "Accounting",
  },
  {
    id: 108,
    fullName: "Regan Swayne",
    avatar: "https://robohash.org/temporibusquamipsa.png?size=50x50&set=set1",
    university: "Arab Open University, Kuwait Branch",
    department: "Marketing",
  },
  {
    id: 109,
    fullName: "Tori Labbet",
    avatar: "https://robohash.org/quosauteos.png?size=50x50&set=set1",
    university: "Multimedia University of Kenya",
    department: "Sales",
  },
  {
    id: 110,
    fullName: "Adriano Donati",
    avatar: "https://robohash.org/autcupiditatevitae.png?size=50x50&set=set1",
    university: "Mizan Tepi University",
    department: "Engineering",
  },
  {
    id: 111,
    fullName: "Skye Woloschinski",
    avatar: "https://robohash.org/quosnoncum.png?size=50x50&set=set1",
    university: "Universitas Ibn Chaldun Jakarta",
    department: "Training",
  },
  {
    id: 112,
    fullName: "Brita Daniello",
    avatar: "https://robohash.org/namassumendaminus.png?size=50x50&set=set1",
    university: "Modern University for the Humanities",
    department: "Marketing",
  },
  {
    id: 113,
    fullName: "Darb Dodell",
    avatar: "https://robohash.org/quiculpavelit.png?size=50x50&set=set1",
    university: "Universidad Arcis",
    department: "Business Development",
  },
  {
    id: 114,
    fullName: "Paulie Davson",
    avatar: "https://robohash.org/idestnostrum.png?size=50x50&set=set1",
    university: "Christian Brothers University",
    department: "Engineering",
  },
  {
    id: 115,
    fullName: "Tore Parkey",
    avatar: "https://robohash.org/delectusquoscommodi.png?size=50x50&set=set1",
    university:
      "Teacher Training College of Revalidation, Rehabilitation and Physical Education",
    department: "Sales",
  },
  {
    id: 116,
    fullName: "Lewes Aleshintsev",
    avatar: "https://robohash.org/voluptatumadqui.png?size=50x50&set=set1",
    university: "Universiti Malaya",
    department: "Marketing",
  },
  {
    id: 117,
    fullName: "Agneta Christin",
    avatar: "https://robohash.org/quasidignissimosat.png?size=50x50&set=set1",
    university: "Institute of Teachers Education, Sultan Abdul Halim",
    department: "Legal",
  },
  {
    id: 118,
    fullName: "Chelsie Willoughway",
    avatar: "https://robohash.org/etutquasi.png?size=50x50&set=set1",
    university: "St. Andrew's University",
    department: "Business Development",
  },
  {
    id: 119,
    fullName: "Forester Leneham",
    avatar: "https://robohash.org/utetvoluptatem.png?size=50x50&set=set1",
    university: "University of Science, Arts and Technology",
    department: "Accounting",
  },
  {
    id: 120,
    fullName: "Vally Kubik",
    avatar: "https://robohash.org/eosquibusdamipsum.png?size=50x50&set=set1",
    university: "Fuji Women's College",
    department: "Human Resources",
  },
  {
    id: 121,
    fullName: "Elbertina Menzies",
    avatar: "https://robohash.org/velpossimuserror.png?size=50x50&set=set1",
    university: "Millersville University of Pennsylvania",
    department: "Human Resources",
  },
  {
    id: 122,
    fullName: "Jasper Bortoli",
    avatar: "https://robohash.org/essefugiatarchitecto.png?size=50x50&set=set1",
    university: "National University of Computer & Emerging Sciences",
    department: "Services",
  },
  {
    id: 123,
    fullName: "Philomena Pougher",
    avatar: "https://robohash.org/veletsed.png?size=50x50&set=set1",
    university: "Centro Universitário de Araraquara",
    department: "Business Development",
  },
  {
    id: 124,
    fullName: "Elijah Fulker",
    avatar:
      "https://robohash.org/impeditmolestiasoccaecati.png?size=50x50&set=set1",
    university: "Royal College of Physicians of Ireland",
    department: "Accounting",
  },
  {
    id: 125,
    fullName: "Esma Steinhammer",
    avatar: "https://robohash.org/omnisdolorqui.png?size=50x50&set=set1",
    university: "Southwestern Christian University",
    department: "Support",
  },
  {
    id: 126,
    fullName: "Thelma Pimblett",
    avatar: "https://robohash.org/adipisciminimaqui.png?size=50x50&set=set1",
    university: "University of Mobile",
    department: "Accounting",
  },
  {
    id: 127,
    fullName: "Lilah Windrus",
    avatar: "https://robohash.org/teneturquivoluptates.png?size=50x50&set=set1",
    university: 'Physical Education Academy "Eugeniusz Piasecki" in Poznan',
    department: "Training",
  },
  {
    id: 128,
    fullName: "Zonda Sumption",
    avatar: "https://robohash.org/inquicorrupti.png?size=50x50&set=set1",
    university: "Fachhochschule Burgenland",
    department: "Engineering",
  },
  {
    id: 129,
    fullName: "Joellen Seville",
    avatar: "https://robohash.org/quiilloenim.png?size=50x50&set=set1",
    university: "Tui Online University",
    department: "Support",
  },
  {
    id: 130,
    fullName: "Ivonne Timbs",
    avatar: "https://robohash.org/facilisquasinventore.png?size=50x50&set=set1",
    university: "Universidad de Nariño",
    department: "Services",
  },
  {
    id: 131,
    fullName: "Sisely Morewood",
    avatar: "https://robohash.org/pariaturetsapiente.png?size=50x50&set=set1",
    university: "Université de Yaoundé I",
    department: "Accounting",
  },
  {
    id: 132,
    fullName: "Duffy Golde",
    avatar: "https://robohash.org/eosquiadolor.png?size=50x50&set=set1",
    university: "Technical University of Poznan",
    department: "Accounting",
  },
  {
    id: 133,
    fullName: "Elspeth Chesser",
    avatar: "https://robohash.org/culpasaepetempora.png?size=50x50&set=set1",
    university: "Postgraduate Institute of Agriculture (PGIA)",
    department: "Services",
  },
  {
    id: 134,
    fullName: "Archaimbaud Brimfield",
    avatar:
      "https://robohash.org/consecteturmolestiaenumquam.png?size=50x50&set=set1",
    university: "Mount St. Mary College",
    department: "Human Resources",
  },
  {
    id: 135,
    fullName: "Danny Houston",
    avatar: "https://robohash.org/magnierrorveritatis.png?size=50x50&set=set1",
    university: "Memorial University of Newfoundland",
    department: "Training",
  },
  {
    id: 136,
    fullName: "Reinaldos Heard",
    avatar: "https://robohash.org/utodioullam.png?size=50x50&set=set1",
    university: "Cheljabinsk State Institute of Teacher Training",
    department: "Human Resources",
  },
  {
    id: 137,
    fullName: "Oralle Milbourn",
    avatar:
      "https://robohash.org/totamquibusdamcommodi.png?size=50x50&set=set1",
    university: "University of Michigan - Flint",
    department: "Human Resources",
  },
  {
    id: 138,
    fullName: "Lavina Eyam",
    avatar: "https://robohash.org/nesciuntquiaomnis.png?size=50x50&set=set1",
    university: "Medizinische Hochschule Hannover",
    department: "Support",
  },
  {
    id: 139,
    fullName: "Osborne Gai",
    avatar: "https://robohash.org/initaqueet.png?size=50x50&set=set1",
    university: "St. Petersburg State Marine Technical University",
    department: "Training",
  },
  {
    id: 140,
    fullName: "Caitrin Capaldo",
    avatar: "https://robohash.org/quirepudiandaeeos.png?size=50x50&set=set1",
    university: "Moscow State Automobile and Road Technical University",
    department: "Legal",
  },
  {
    id: 141,
    fullName: "Rhiamon Poinsett",
    avatar:
      "https://robohash.org/repellatpraesentiumdolor.png?size=50x50&set=set1",
    university: "Guangdong University of Technology",
    department: "Engineering",
  },
  {
    id: 142,
    fullName: "Lucio Rounsefull",
    avatar:
      "https://robohash.org/eligendiconsequunturcorrupti.png?size=50x50&set=set1",
    university: "Keimyung University",
    department: "Legal",
  },
  {
    id: 143,
    fullName: "Charlton Morkham",
    avatar:
      "https://robohash.org/corporisassumendarerum.png?size=50x50&set=set1",
    university: "Chicago State University",
    department: "Human Resources",
  },
  {
    id: 144,
    fullName: "Boot MacGiolla",
    avatar: "https://robohash.org/voluptasautplaceat.png?size=50x50&set=set1",
    university: "Spartan University of Health Sciences",
    department: "Engineering",
  },
  {
    id: 145,
    fullName: "Karlie Chapling",
    avatar:
      "https://robohash.org/consequaturaccusantiumab.png?size=50x50&set=set1",
    university: "Lillehammer University College",
    department: "Support",
  },
  {
    id: 146,
    fullName: "Leandra Phillins",
    avatar:
      "https://robohash.org/namasperioresdoloremque.png?size=50x50&set=set1",
    university: "Madhya Pradesh Bhoj (Open) University",
    department: "Research and Development",
  },
  {
    id: 147,
    fullName: "Lezlie Menauteau",
    avatar: "https://robohash.org/dolormaioresqui.png?size=50x50&set=set1",
    university: "University of Nijenrode",
    department: "Marketing",
  },
  {
    id: 148,
    fullName: "Adria Glisane",
    avatar: "https://robohash.org/verodeseruntsit.png?size=50x50&set=set1",
    university: "University of West Los Angeles",
    department: "Research and Development",
  },
  {
    id: 149,
    fullName: "Jerome Skinley",
    avatar: "https://robohash.org/etullamamet.png?size=50x50&set=set1",
    university: "Universidad del Azuay",
    department: "Engineering",
  },
  {
    id: 150,
    fullName: "Ingmar Beecker",
    avatar: "https://robohash.org/utquopraesentium.png?size=50x50&set=set1",
    university: "Darul Hikmah Islamic College",
    department: "Legal",
  },
  {
    id: 151,
    fullName: "Charis Leirmonth",
    avatar: "https://robohash.org/quiaautpossimus.png?size=50x50&set=set1",
    university: "Odlar Yurdu University",
    department: "Business Development",
  },
  {
    id: 152,
    fullName: "Lurleen Stranaghan",
    avatar: "https://robohash.org/sedexpeditanatus.png?size=50x50&set=set1",
    university: "Goa University",
    department: "Business Development",
  },
  {
    id: 153,
    fullName: "Nero Ruperto",
    avatar:
      "https://robohash.org/consequaturpossimusaut.png?size=50x50&set=set1",
    university: "Tajikistan International University",
    department: "Support",
  },
  {
    id: 154,
    fullName: "Athene Joyson",
    avatar: "https://robohash.org/idinciduntassumenda.png?size=50x50&set=set1",
    university: "Université d'Artois",
    department: "Services",
  },
  {
    id: 155,
    fullName: "Tildi Joutapaitis",
    avatar: "https://robohash.org/adquimagnam.png?size=50x50&set=set1",
    university: "Fukuoka University of Education",
    department: "Marketing",
  },
  {
    id: 156,
    fullName: "Allegra Beceril",
    avatar: "https://robohash.org/modihicquo.png?size=50x50&set=set1",
    university: "University of Kragujevac",
    department: "Product Management",
  },
  {
    id: 157,
    fullName: "Sondra Dumbleton",
    avatar: "https://robohash.org/seddoloribusquasi.png?size=50x50&set=set1",
    university: "South China Agricultural University",
    department: "Marketing",
  },
  {
    id: 158,
    fullName: "Rodrigo Mottram",
    avatar:
      "https://robohash.org/architectodoloresenim.png?size=50x50&set=set1",
    university: "Technological Education Institute of Lamia",
    department: "Research and Development",
  },
  {
    id: 159,
    fullName: "Loree Pasby",
    avatar: "https://robohash.org/voluptateautemut.png?size=50x50&set=set1",
    university: "University of Nebraska - Omaha",
    department: "Product Management",
  },
  {
    id: 160,
    fullName: "Lila Gebbie",
    avatar: "https://robohash.org/fugitdolorumquae.png?size=50x50&set=set1",
    university: "National Open University of Nigeria",
    department: "Research and Development",
  },
  {
    id: 161,
    fullName: "Leonora Wadly",
    avatar: "https://robohash.org/ettotamsoluta.png?size=50x50&set=set1",
    university: "Halic University",
    department: "Legal",
  },
  {
    id: 162,
    fullName: "Roxanne Pohling",
    avatar: "https://robohash.org/quiadoloribusaut.png?size=50x50&set=set1",
    university: "Mindanao State University",
    department: "Support",
  },
  {
    id: 163,
    fullName: "Kippie Garnsworthy",
    avatar: "https://robohash.org/rationemollitianon.png?size=50x50&set=set1",
    university: "National Ribat University",
    department: "Services",
  },
  {
    id: 164,
    fullName: "Hurlee Dinesen",
    avatar: "https://robohash.org/autemrerumdolorem.png?size=50x50&set=set1",
    university: "John F. Kennedy University",
    department: "Services",
  },
  {
    id: 165,
    fullName: "Kendall Goadsby",
    avatar: "https://robohash.org/quianemoimpedit.png?size=50x50&set=set1",
    university: "Al-Azhar University of Gaza",
    department: "Product Management",
  },
  {
    id: 166,
    fullName: "Olwen Allender",
    avatar: "https://robohash.org/minimainut.png?size=50x50&set=set1",
    university: "Cedarville College",
    department: "Training",
  },
  {
    id: 167,
    fullName: "Mariana Goodyear",
    avatar:
      "https://robohash.org/quisquamvoluptasanimi.png?size=50x50&set=set1",
    university: "Universidad Mesoamericana de San Agustín",
    department: "Services",
  },
  {
    id: 168,
    fullName: "Kipp Goroni",
    avatar: "https://robohash.org/quiquaeunde.png?size=50x50&set=set1",
    university: "Centro Regional Universitário de Espiríto Santo do Pinhal",
    department: "Product Management",
  },
  {
    id: 169,
    fullName: "Zarah Merritt",
    avatar:
      "https://robohash.org/quialaudantiumconsequatur.png?size=50x50&set=set1",
    university: "Belgorod State Technical University",
    department: "Human Resources",
  },
  {
    id: 170,
    fullName: "Terrence Davids",
    avatar:
      "https://robohash.org/laudantiumistequibusdam.png?size=50x50&set=set1",
    university: "University of Science and Arts of Oklahoma",
    department: "Human Resources",
  },
  {
    id: 171,
    fullName: "Giffer Brody",
    avatar: "https://robohash.org/fugaminusquis.png?size=50x50&set=set1",
    university: "Western Delta University",
    department: "Sales",
  },
  {
    id: 172,
    fullName: "Lane Regenhardt",
    avatar: "https://robohash.org/evenietexpeditaquia.png?size=50x50&set=set1",
    university: "Green Mountain College",
    department: "Research and Development",
  },
  {
    id: 173,
    fullName: "Hubert Furber",
    avatar: "https://robohash.org/ipsafugitmolestiae.png?size=50x50&set=set1",
    university: "Omar Al-Mukhtar University",
    department: "Sales",
  },
  {
    id: 174,
    fullName: "Nils Straker",
    avatar: "https://robohash.org/quiautemerror.png?size=50x50&set=set1",
    university: "Westminster International University in Tashkent",
    department: "Product Management",
  },
  {
    id: 175,
    fullName: "Krissie Pidcock",
    avatar: "https://robohash.org/voluptatemquodminus.png?size=50x50&set=set1",
    university: "Columbia University",
    department: "Sales",
  },
  {
    id: 176,
    fullName: "Linda Coetzee",
    avatar:
      "https://robohash.org/doloremrecusandaeiure.png?size=50x50&set=set1",
    university: "Adeyemi College of Education",
    department: "Engineering",
  },
  {
    id: 177,
    fullName: "Darda Adolf",
    avatar: "https://robohash.org/totaminventoreminima.png?size=50x50&set=set1",
    university: "Universidad Catolica de Azogues",
    department: "Legal",
  },
  {
    id: 178,
    fullName: "Thoma Covotto",
    avatar:
      "https://robohash.org/perspiciatisutcupiditate.png?size=50x50&set=set1",
    university: "Mount St. Mary's College California",
    department: "Product Management",
  },
  {
    id: 179,
    fullName: "Hilliary Cowey",
    avatar:
      "https://robohash.org/sapientenecessitatibussit.png?size=50x50&set=set1",
    university: "Academy of Performing Arts, Film and TV Fakulty",
    department: "Training",
  },
  {
    id: 180,
    fullName: "Charyl Daltry",
    avatar: "https://robohash.org/quisetrepellendus.png?size=50x50&set=set1",
    university: "Western University",
    department: "Engineering",
  },
  {
    id: 181,
    fullName: "Katherine Pellew",
    avatar: "https://robohash.org/minustemporeillum.png?size=50x50&set=set1",
    university: "Ulyanovsk State Technical University",
    department: "Engineering",
  },
  {
    id: 182,
    fullName: "Delcine Doolan",
    avatar: "https://robohash.org/nonisteprovident.png?size=50x50&set=set1",
    university: "Zhejiang Gongshang University",
    department: "Marketing",
  },
  {
    id: 183,
    fullName: "Adoree Clulow",
    avatar:
      "https://robohash.org/inventorequisquamasperiores.png?size=50x50&set=set1",
    university: "Dubai Medical College for Girls",
    department: "Training",
  },
  {
    id: 184,
    fullName: "Euell Shrive",
    avatar: "https://robohash.org/utindicta.png?size=50x50&set=set1",
    university: "Keio University",
    department: "Marketing",
  },
  {
    id: 185,
    fullName: "Claudette Haggerwood",
    avatar: "https://robohash.org/placeatquaequidem.png?size=50x50&set=set1",
    university: "Alsadrain University",
    department: "Business Development",
  },
  {
    id: 186,
    fullName: "Waiter Balderston",
    avatar:
      "https://robohash.org/placeatdignissimosqui.png?size=50x50&set=set1",
    university: "Seijo University",
    department: "Business Development",
  },
  {
    id: 187,
    fullName: "Lena Jiles",
    avatar: "https://robohash.org/istelaboriosammodi.png?size=50x50&set=set1",
    university: "Hachinohe Institute of Technology",
    department: "Research and Development",
  },
  {
    id: 188,
    fullName: "Tiffany Elcocks",
    avatar: "https://robohash.org/quipraesentiumbeatae.png?size=50x50&set=set1",
    university: "Doho University",
    department: "Sales",
  },
  {
    id: 189,
    fullName: "Demetris Reilingen",
    avatar: "https://robohash.org/rerumsolutavoluptas.png?size=50x50&set=set1",
    university: "College Misericordia",
    department: "Services",
  },
  {
    id: 190,
    fullName: "Ely Peschka",
    avatar: "https://robohash.org/modisuscipitomnis.png?size=50x50&set=set1",
    university: "B.P.Koirala Institute of Health Sciences",
    department: "Research and Development",
  },
  {
    id: 191,
    fullName: "Alvinia Montford",
    avatar: "https://robohash.org/nisiimpeditut.png?size=50x50&set=set1",
    university: "Mahanakorn University of Technology",
    department: "Marketing",
  },
  {
    id: 192,
    fullName: "Katharyn Clampe",
    avatar: "https://robohash.org/temporibusquiaut.png?size=50x50&set=set1",
    university: "Université d'Etat d'Haiti",
    department: "Business Development",
  },
  {
    id: 193,
    fullName: "Livvie Maine",
    avatar:
      "https://robohash.org/necessitatibusetaspernatur.png?size=50x50&set=set1",
    university: "Escuela Superiore de Administración Pública",
    department: "Product Management",
  },
  {
    id: 194,
    fullName: "Eda Pearcy",
    avatar: "https://robohash.org/adrepellatmollitia.png?size=50x50&set=set1",
    university: "Université de Jendouba",
    department: "Accounting",
  },
  {
    id: 195,
    fullName: "Pyotr Crigin",
    avatar: "https://robohash.org/abquasconsequuntur.png?size=50x50&set=set1",
    university: "Universität Fridericana Karlsruhe (Technische Hochschule)",
    department: "Business Development",
  },
  {
    id: 196,
    fullName: "Nara Hawket",
    avatar: "https://robohash.org/etfugafacere.png?size=50x50&set=set1",
    university: "Private College of Dentistry and Pharmacy",
    department: "Support",
  },
  {
    id: 197,
    fullName: "Vick Elnor",
    avatar:
      "https://robohash.org/molestiasmaioressaepe.png?size=50x50&set=set1",
    university: "State University of New York College at Purchase",
    department: "Human Resources",
  },
  {
    id: 198,
    fullName: "Gabey Frangleton",
    avatar: "https://robohash.org/rerumliberoet.png?size=50x50&set=set1",
    university: "Volga State Academy of Water Transport",
    department: "Legal",
  },
  {
    id: 199,
    fullName: "Nahum Jaulmes",
    avatar: "https://robohash.org/idnonquo.png?size=50x50&set=set1",
    university: "Ambassador University",
    department: "Product Management",
  },
  {
    id: 200,
    fullName: "Cchaddie Philpott",
    avatar: "https://robohash.org/utsedquo.png?size=50x50&set=set1",
    university: "Semnan University",
    department: "Accounting",
  },
];

data.forEach((v) => {
  const card = document.createElement("div");
  card.className = "card";
  card.insertAdjacentHTML(
    "beforeend",
    `
		<img class="avatar" src=${v.avatar}/>
		<div class="fullName">✨ ${v.fullName}</div>
		<div class="department">🔗 ${v.department}</div>
		<div class="university">🏫 ${v.university}</div>
	`
  );

  const person = document.querySelector(".person");
  person.appendChild(card);

  /**
  const avatar = document.createElement("img");
  const fullName = document.createElement("div");
  const department = document.createElement("div");
  const university = document.createElement("div");

  avatar.src = v.avatar;
  fullName.innerText = v.fullName;
  department.innerText = v.department;
  university.innerText = v.university;
  avatar.className = "avatar";
  fullName.className = "fullName";
  department.className = "department";
  university.className = "university";

  const card = document.createElement("div");
  card.className = "card";
  card.appendChild(avatar);
  card.appendChild(fullName);
  card.appendChild(department);
  card.appendChild(university);

  const person = document.querySelector(".person");
  person.appendChild(card);
*/
});
